# Generated by Django 4.1.1 on 2022-09-13 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=50)),
                ('house_flat', models.CharField(max_length=200)),
                ('road_area', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
