# Generated by Django 4.1.3 on 2022-11-05 10:38

import deliveree_go_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField(default='')),
                ('created_on', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='category_types',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField()),
                ('image', models.FileField(upload_to=deliveree_go_users.models.categoryImage_directory_path)),
            ],
            options={
                'db_table': 'category_types',
            },
        ),
        migrations.CreateModel(
            name='items_list',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=300)),
                ('item_type', models.CharField(max_length=200)),
                ('category_id', models.BigIntegerField()),
                ('category_type', models.CharField(default='', max_length=200)),
                ('item_price', models.FloatField()),
                ('something_extra', models.TextField()),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'items_list',
            },
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=50)),
                ('delivery_address_id', models.IntegerField()),
                ('billing_address_id', models.CharField(max_length=1000)),
                ('rider_tip_aount', models.CharField(max_length=100)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='shops_images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('image', models.FileField(upload_to=deliveree_go_users.models.shopImage_directory_path)),
                ('created_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'shops_images',
            },
        ),
        migrations.CreateModel(
            name='shops_list',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('open_time', models.CharField(default='', max_length=200)),
                ('closing_time', models.CharField(default='', max_length=200)),
                ('menu_data', models.TextField()),
                ('shop_type', models.CharField(default='', max_length=50)),
                ('category_id', models.IntegerField(null=True)),
                ('category_type', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='')),
                ('location', models.TextField()),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'shops_list',
            },
        ),
        migrations.CreateModel(
            name='user_locations',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(max_length=50)),
                ('house_flat', models.CharField(max_length=200)),
                ('road_area', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'user_locations',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default='', max_length=200, unique=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
