# Generated by Django 4.1.3 on 2022-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree_go_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_list',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('item_price', models.CharField(max_length=20)),
                ('created_on', models.CharField(max_length=200)),
            ],
        ),
    ]
