# Generated by Django 4.1.3 on 2022-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree_go_users', '0002_cart_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_list',
            name='modified_on',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart_list',
            name='total_item',
            field=models.IntegerField(null=True),
        ),
    ]
