# Generated by Django 4.1.1 on 2022-09-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree_go_users', '0002_users_user_locations_email_user_locations_uid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_locations',
            table='user_locations',
        ),
    ]
