# Generated by Django 4.1.1 on 2022-09-16 10:46

import deliveree_go_users.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree_go_users', '0003_alter_user_locations_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_types',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
            ],
            options={
                'db_table': 'category_types',
            },
        ),
        migrations.CreateModel(
            name='items_list',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=300)),
                ('item_type', models.CharField(max_length=200)),
                ('category_id', models.BigIntegerField()),
                ('category_type', models.CharField(default='', max_length=200)),
                ('item_price', models.FloatField()),
                ('something_extra', models.TextField()),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'items_list',
            },
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=50)),
                ('delivery_address_id', models.IntegerField()),
                ('billing_address_id', models.CharField(max_length=1000)),
                ('rider_tip_aount', models.CharField(max_length=100)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=200)),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='shops_list',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('open_time', models.CharField(default='', max_length=200)),
                ('closing_time', models.CharField(default='', max_length=200)),
                ('menu_data', models.TextField()),
                ('shop_type', models.CharField(default='', max_length=50)),
                ('category_id', models.BigIntegerField()),
                ('category_type', models.CharField(default='', max_length=200)),
                ('images', models.FileField(upload_to=deliveree_go_users.models.shopImage_directory_path)),
                ('location', models.TextField()),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_on', models.CharField(default='', max_length=300)),
                ('modified_on', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'shops_list',
            },
        ),
        migrations.RenameField(
            model_name='user_locations',
            old_name='id',
            new_name='address_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='user_locations',
            name='created_on',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user_locations',
            name='modified_on',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='users',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='created_on',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='modified_on',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
