# Generated by Django 4.1.1 on 2022-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveree_go_users', '0006_addratings_reviews_shops_list_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops_list',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
